import json
import os
from datos import Cursos as cola


# Paso 1: Crear el diccionario con los cursos y sus categorías.
cursos_categorias = {
    '0101 AREA MATEMATICA BASICA 1': 'Matematicas',
    '0103 AREA MATEMATICA BASICA 2': 'Matematicas',
    '0107 AREA MATEMATICA INTERMEDIA 1': 'Matematicas',
    '0112 AREA MATEMATICA INTERMEDIA 2': 'Matematicas',
    '0114 AREA MATEMATICA INTERMEDIA 3': 'Matematicas',
    '0118 MATEMATICA APLICADA 1': 'Matematicas',
    '0116 MATEMATICA APLICADA 3': 'Matematicas',
    '0120 MATEMATICA APLICADA 2': 'Matematicas',
    '0122 MATEMATICA APLICADA 4': 'Matematicas',
    '0123 MATEMATICA APLICADA 5': 'Matematicas',
    '0960 MATEMATICA PARA COMPUTACION 1': 'Matematicas',
    '0962 MATEMATICA PARA COMPUTACION 2': 'Matematicas',
    # Fisica
    '0147 FISICA BASICA': 'Fisica',
    '0150 FISICA 1': 'Fisica',
    '0152 FISICA 2': 'Fisica',
    '0154 FISICA 3': 'Fisica',
    '0156 FISICA 4': 'Fisica',
    '0170 MECANICA ANALITICA 1': 'Fisica',
    '0172 MECANICA ANALITICA 2': 'Fisica',
    '0173 ANALISIS MECANICO': 'Fisica',
    '0200 INGENIERIA ELECTRICA 1': 'Fisica',
    '0202 INGENIERIA ELECTRICA 2': 'Fisica',
    '0210 TEORIA ELECTROMAGNETICA 1': 'Fisica',
    '0211 TEORIA ELECTROMAGNETICA 2': 'Fisica',
    '0212 CONVERSION DE ENERGIA ELECTROMECANICA 1': 'Fisica',
    '0213 CONVERSION DE ENERGIA ELECTROMECANICA 2': 'Fisica',
    '0250 MECANICA DE FLUIDOS': 'Fisica',
    '0380 FISICO QUIMICA 1': 'Fisica',
    '0382 FISICO QUIMICA 2': 'Fisica',
    '0390 TERMODINAMICA 1': 'Fisica',
    '0392 TERMODINAMICA 2': 'Fisica',
    '0394 TERMODINAMICA 3': 'Fisica',
    '0396 TERMODINAMICA 4': 'Fisica',
    '0412 FLUJO DE FLUIDOS': 'Fisica',
    # Electricidad y electronica
    '0200 INGENIERIA ELECTRICA 1': 'ElectricidadyElectronica',
    '0204 CIRCUITOS ELECTRICOS 1': 'ElectricidadyElectronica',
    '0202 INGENIERIA ELECTRICA 2': 'ElectricidadyElectronica',
    '0206 CIRCUITOS ELECTRICOS 2': 'ElectricidadyElectronica',
    '0208 INSTALACIONES ELECTRICAS': 'ElectricidadyElectronica',
    '0201 INSTALACIONES ELECTRICAS (CIVIL)': 'ElectricidadyElectronica',
    '0209 INSTALACION DE EQUIPOS ELECTRONICOS': 'ElectricidadyElectronica',
    '0214 MAQUINAS ELECTRICAS': 'ElectricidadyElectronica',
    '0218 LINEAS DE TRANSMISION': 'ElectricidadyElectronica',
    '0219 TRANSMISION Y DISTRIBUCION': 'ElectricidadyElectronica',
    '0220 ANALISIS DE SISTEMAS DE POTENCIA 1': 'ElectricidadyElectronica',
    '0221 SISTEMAS DE GENERACION': 'ElectricidadyElectronica',
    '0222 PROTECCION DE SISTEMAS DE POTENCIA': 'ElectricidadyElectronica',
    '0224 ALTA TENSION': 'ElectricidadyElectronica',
    '0230 INSTRUMENTACION ELECTRICA': 'ElectricidadyElectronica',
    '0232 ELECTRONICA 1': 'ElectricidadyElectronica',
    '0233 ELECTRONICA APLICADA 1': 'ElectricidadyElectronica',
    '0234 ELECTRONICA 4': 'ElectricidadyElectronica',
    '0235 ROBOTICA': 'ElectricidadyElectronica',
    '0239 ELECTRONICA APLICADA 2': 'ElectricidadyElectronica',
    '0240 ELECTRONICA 2': 'ElectricidadyElectronica',
    '0241 RADIOCOMUNICACIONES TERRESTRES': 'ElectricidadyElectronica',
    '0246 ELECTRONICA 3': 'ElectricidadyElectronica',
    '0248 ELECTRONICA 5': 'ElectricidadyElectronica',
    '0249 ELECTRONICA 6': 'ElectricidadyElectronica',
    '0462 ELECTRICIDADYELECTRONICA BASICA': 'ElectricidadyElectronica',
    '0769 INTRODUCCION A LA PROGRAMACION DE COMPUTADORAS': 'ElectricidadyElectronica',
    '0980 PROYECTOS DE COMPUTACION APLICADA A I.E.': 'ElectricidadyElectronica',
    '0991 LENGUAJES DE PROGRAMACION APLICADOS A I.E.': 'ElectricidadyElectronica',
    '0090 PROGRAMACION DE COMPUTADORAS 1': 'ElectricidadyElectronica',
    '0092 PROGRAMACION DE COMPUTADORAS 2': 'ElectricidadyElectronica',
    #quimica
    '0348 QUIMICA GENERAL 1': 'Quimica',
    '0349 QUIMICA PARA INGENIERIA CIVIL': 'Quimica',
    '0352 QUIMICA 2': 'Quimica',
    '0358 QUIMICA ORGANICA 1': 'Quimica',
    '0360 QUIMICA ORGANICA 2': 'Quimica',
    '0361 BIOQUIMICA 1': 'Quimica',
    '0370 QUIMICA AMBIENTAL': 'Quimica',
    '0380 FISICO QUIMICA 1': 'Quimica',
    '0382 FISICO QUIMICA 2': 'Quimica',
    '0398 CINETICA DE PROCESOS QUIMICOS': 'Quimica',
    '0409 SEPARACION POR MEDIO DE MEMBRANAS SELECTIVAS': 'Quimica',
    '0410 BALANCE DE MASA Y ENERGIA': 'Quimica',
    '0412 FLUJO DE FLUIDOS': 'Quimica',
    '0432 DINAMICA DE PROCESOS QUIMICOS': 'Quimica',
    '0434 PROCESOS QUIMICOS INDUSTRIALES': 'Quimica',
    '0440 MICROBIOLOGIA': 'Quimica',
    '0442 BIOINGENIERIA 1': 'Quimica',
    '0452 CIENCIA DE LOS MATERIALES': 'Quimica',
    '0486 DISEÑO DE PLANTAS': 'Quimica',
    '0027 BIOLOGIA': 'Quimica',
    # ciencias Hidro
    '0193 MANEJO DE CUENCAS HIDROGRAFICAS': 'CienciasHidro',
    '0252 HIDRAULICA': 'CienciasHidro',
    '0258 MAQUINASHIDRAULICAS': 'CienciasHidro',
    '0262 AGUAS SUBTERRANEAS': 'CienciasHidro',
    '0286 HIDRAULICA DE CANALES': 'CienciasHidro',
    #construccion
    '0300 RESISTENCIA DE MATERIALES 1': 'Construccion',
    '0302 RESISTENCIA DE MATERIALES 2': 'Construccion',
    '0311 ANALISIS ESTRUCTURAL': 'Construccion',
    '0314 CONCRETO ARMADO 1': 'Construccion',
    '0316 CONCRETO ARMADO 2': 'Construccion',
    '0318 CIMENTACIONES 1': 'Construccion',
    '0322 DISEÑO ESTRUCTURAL 1': 'Construccion',
    '0324 DISEÑO ESTRUCTURAL 2': 'Construccion',
    '0332 PUENTES': 'Construccion',
    '0346 METODOS DE CONSTRUCCION Y SUPERVISION DE OBRAS': 'Construccion',
    '0368 PRINCIPIOS DE METROLOGIA': 'Construccion',
    '0450 GEOLOGIA': 'Construccion',
    '0452 CIENCIA DE LOS MATERIALES': 'Construccion',
    '0453 MATERIALES DE CONSTRUCCION 1': 'Construccion',
    '0455 MATERIALES DE CONSTRUCCION 2': 'Construccion',
    '0458 MECANICA DE SUELOS 1': 'Construccion',
    '0460 PAVIMENTOS': 'Construccion',
    '0550 VIAS TERRESTRES 1': 'Construccion',
    '5009 INTERPRETACION DE PLANOS': 'Construccion',
    '0075 DIBUJO COMPUTARIZADO': 'Construccion',
    '0080 TOPOGRAFIA 1': 'Construccion',
    '0082 TOPOGRAFIA 2': 'Construccion',
    '0084 TOPOGRAFIA 3': 'Construccion',
    #Administracion industial
    '0421 GESTION TOTAL DE LA CALIDAD': 'AdministracionIndustrial',
    '0423 EXTRACCIONES INDUSTRIALES': 'AdministracionIndustrial',
    '0434 PROCESOS QUIMICOS INDUSTRIALES': 'AdministracionIndustrial',
    '0437 CONTROL DE CONTAMINANTES INDUSTRIALES': 'AdministracionIndustrial',
    '0454 METALURGIA Y METALOGRAFIA': 'AdministracionIndustrial',
    '0482 OPERACIONES Y PROCESOS EN LA INDUSTRIA FARMACEUTICA': 'AdministracionIndustrial',
    '0502 REFRIGERACION Y AIRE ACONDICIONADO': 'AdministracionIndustrial',
    '0520 PROCESOS DE MANUFACTURA 1': 'AdministracionIndustrial',
    '0522 PROCESOS DE MANUFACTURA 2': 'AdministracionIndustrial',
    '0606 ANALISIS DE SISTEMAS INDUSTRIALES': 'AdministracionIndustrial',
    '0608 INTROD DE PROYECTOS GERENCIALES': 'AdministracionIndustrial',
    '0630 INGENIERIA DE LA PRODUCCION': 'AdministracionIndustrial',
    '0632 INGENIERIA DE PLANTAS': 'AdministracionIndustrial',
    '0634 INGENIERIA DE METODOS': 'AdministracionIndustrial',
    '0636 DISEÑO PARA LA PRODUCCION': 'AdministracionIndustrial',
    '0637 DISEÑO INDUSTRIAL': 'AdministracionIndustrial',
    '0638 CONTROLES INDUSTRIALES': 'AdministracionIndustrial',
    '0639 CONTROL ESTADISTICO DE LA CALIDAD': 'AdministracionIndustrial',
    '0640 CONTROL DE LA PRODUCCION': 'AdministracionIndustrial',
    '0642 SEGURIDAD E HIGIENE INDUSTRIAL': 'AdministracionIndustrial',
    '0653 INGENIERIA DE COSTOS': 'AdministracionIndustrial',
    '0706 PREPARACION Y EVALUACION DE PROYECTOS 1': 'AdministracionIndustrial',
    '0708 PREPARACION Y EVALUACION DE PROYECTOS 2': 'AdministracionIndustrial',
    '0710 PLANEAMIENTO': 'AdministracionIndustrial',
    '0238 AUTOMATIZACIONINDUSTRIAL': 'AdministracionIndustrial',
    '0236 SISTEMAS DE CONTROL 1': 'AdministracionIndustrial',
    '0022 PSICOLOGIA INDUSTRIAL': 'AdministracionIndustrial',
    #ambiental
    '0284 SANEAMIENTO AMBIENTAL': 'Ambiental',
    '0288 INTRODUCCION AL ESTUDIO DE IMPACTO AMBIENTAL': 'Ambiental',
    '0307 TIPOLOGIA ESTRUCTURAL': 'Ambiental',
    '0335 GESTION DE DESASTRES': 'Ambiental',
    '0370 QUIMICA AMBIENTAL': 'Ambiental',
    '0431 ECONOMIA DE LOS RECURSOS NATURALES RENOVABLES': 'Ambiental',
    '0450 GEOLOGIA': 'Ambiental',
    '0474 INTRODUCCION A LA INGENIERIA PETROLERA': 'Ambiental',
    '0478 PETROLOGIA': 'Ambiental',
    '0486 DISEÑO DE PLANTAS': 'Ambiental',
    '0879 CLIMATOLOGIA': 'Ambiental',
    '7935 SEMINARIO DE INVESTIGACION AMBIENTAL': 'Ambiental',
    '0028 ECOLOGIA': 'Ambiental',
    #seguridad e higiene
    '0280 INGENIERIA SANITARIA 1': 'SeguridadHigiene',
    '0282 INGENIERIA SANITARIA 2': 'SeguridadHigiene',
    '0284 SANEAMIENTO AMBIENTAL': 'SeguridadHigiene',
    '0441 MANEJO ADECUADO DE LOS DESECHOS SOLIDOS': 'SeguridadHigiene',
    '0437 CONTROL DE CONTAMINANTES INDUSTRIALES': 'SeguridadHigiene',
    '0511 MANTENIMIENTO DE HOSPITALES 1': 'SeguridadHigiene',
    '0642 SEGURIDAD E HIGIENE INDUSTRIAL': 'SeguridadHigiene',
    '5004 INSTALACIONES SANITARIAS, DRENAJES, AGUA POTABLE Y ELECTRICIDAD': 'SeguridadHigiene',
    '5005 HIGIENE Y PROTECCION EN LAS OBRAS DE CONSTRUCCION': 'SeguridadHigiene',
    '0670 LEGISLACION AMBIENTAL 2': 'SeguridadHigiene',
    #Mecanica
    '0504 MOTORES DE COMBUSTION INTERNA': 'Mecanica',
    '0506 PLANTAS DE VAPOR': 'Mecanica',
    '0508 MONTAJE Y MANTENIMIENTO DE EQUIPO': 'Mecanica',
    '0510 INSTALACIONES MECANICAS': 'Mecanica',
    '0512 INSTRUMENTACION MECANICA': 'Mecanica',
    '0524 DISEÑO DE MAQUINAS 1': 'Mecanica',
    '0530 MECANISMOS': 'Mecanica',
    #Estadistica
    '0362 ANALISIS CUALITATIVO': 'Estadistica',
    '0653 INGENIERIA DE COSTOS': 'Estadistica',
    '0650 CONTABILIDAD 1': 'Estadistica',
    '0652 CONTABILIDAD 2': 'Estadistica',
    '0654 CONTABILIDAD 3': 'Estadistica',
    '0669 ECONOMIA INDUSTRIAL': 'Estadistica',
    '0700 INGENIERIA ECONOMICA 1': 'Estadistica',
    '0702 INGENIERIA ECONOMICA 2': 'Estadistica',
    '0704 INGENIERIA ECONOMICA 3': 'Estadistica',
    '0732 ESTADISTICA 1': 'Estadistica',
    '0734 ESTADISTICA 2': 'Estadistica',
    '0736 ANALISIS PROBABILISTICO': 'Estadistica',
    '0014 ECONOMIA': 'Estadistica',
    #informatica
    '0610 INFORMATICA': 'Informatica',
    '0667 PROGRAMACION COMERCIAL 1': 'Informatica',
    #Ciencias de la computacion
    '0720 MODELACION Y SIMULACION 2': 'CienciasComputacion',
    '0722 TEORIA DE SISTEMAS 1': 'CienciasComputacion',
    '0724 TEORIA DE SISTEMAS 2': 'CienciasComputacion',
    '0729 MODELACION Y SIMULACION 1': 'CienciasComputacion',
    '0770 INTRODUCCION A LA PROGRAMACION Y COMPUTACION 1': 'CienciasComputacion',
    '0771 INTRODUCCION A LA PROGRAMACION Y COMPUTACION 2': 'CienciasComputacion',
    '0772 ESTRUCTURAS DE DATOS': 'CienciasComputacion',
    '0773 MANEJO E IMPLEMENTACION DE ARCHIVOS': 'CienciasComputacion',
    '0774 SISTEMAS DE BASES DE DATOS 1': 'CienciasComputacion',
    '0777 ORGANIZACION DE LENGUAJES Y COMPILADORES 1': 'CienciasComputacion',
    '0778 ARQUITECTURA DE COMPUTADORES Y ENSAMBLADORES 1': 'CienciasComputacion',
    '0779 ARQUITECTURA DE COMPUTADORES Y ENSAMBLADORES 2': 'CienciasComputacion',
    '0780 SOFTWARE AVANZADO': 'CienciasComputacion',
    '0781 ORGANIZACION DE LENGUAJES Y COMPILADORES 2': 'CienciasComputacion',
    '0785 ANALISIS Y DISEÑO DE SISTEMAS 2': 'CienciasComputacion',
    '0786 SISTEMAS ORGANIZACIONALES Y GERENCIALES 1': 'CienciasComputacion',
    '0795 LOGICA DE SISTEMAS': 'CienciasComputacion',
    '0796 LENGUAJES FORMALES Y DE PROGRAMACION': 'CienciasComputacion',
    '0964 ORGANIZACION COMPUTACIONAL': 'CienciasComputacion',
    '0968 INTELIGENCIA ARTIFICIAL 2': 'CienciasComputacion',
    '0970 REDES DE COMPUTADORAS 1': 'CienciasComputacion',
    '0972 INTELIGENCIA ARTIFICIAL 1': 'CienciasComputacion',
    '0975 REDES DE COMPUTADORAS 2': 'CienciasComputacion',
    #Administracion
    '0656 ADMINISTRACION DE EMPRESAS 1': 'Administracion',
    '0657 ADMINISTRACION DE EMPRESAS 2': 'Administracion',
    '0658 ADMINISTRACION DE PERSONAL': 'Administracion',
    '0660 MERCADOTECNIA 1': 'Administracion',
    '0661 MERCADOTECNIA 2': 'Administracion',
    '0662 LEGISLACION 1': 'Administracion',
    '0665 MICROECONOMIA': 'Administracion',
    '0666 COSTOS PRESUPUESTOS Y AVALUOS': 'Administracion',
    '0706 PREPARACION Y EVALUACION DE PROYECTOS 1': 'Administracion',
    '0708 PREPARACION Y EVALUACION DE PROYECTOS 2': 'Administracion',
    '5006 APLICABILIDAD DE LOS CONCEPTOS JURIDICOS BASICOS EN MATERIA LABORAL': 'Administracion',
    #Diplomados
    '1023 DIPLOMADO EN ACONDICIONAMIENTO DEL AGUA EN LA INDUSTRIA': 'Diplomados',
    '1025 DIPLOMADO EN ADMINISTRACION DE LA CALIDAD': 'Diplomados',
    '1034 DIPLOMADO EN ADMINISTRACION DE LA CALIDAD EN LA INDUSTRIA ALIMENTICIA': 'Diplomados',
    '1035 DIPLOMADO EN MATEMATICAS DE INGENIERIA': 'Diplomados',
    '1056 DIPLOMADO SEGURIDAD INDUSTRIAL Y SALUD OCUPACIONAL': 'Diplomados',
    '1059 DIPLOMADO BUENAS PRACTICAS DE MAN EN LA IND FARMA Y ALIMENTICIA': 'Diplomados',
    '1060 DIPLOMADO CADENA DE SUMISTROS': 'Diplomados',
    '1065 DIPLOMADO ADMINISTRACION Y COMPETENCIAS': 'Diplomados',
    '1071 DIPLOMADO MANTENIMIENTO INDUSTRIAL': 'Diplomados',
    '1074 DIPLOMADO EN LIDERAZGO DEL TALENTO HUMANO': 'Diplomados',
    '1076 DIPLOMADO EN GESTION GERENCIAL DE OPERACIONES': 'Diplomados',
    '1077 DIPLOMADO EN RECURSOS HUMANOS': 'Diplomados',
    '1084 DIPLOMADO DE PROPIEDAD INTELECTUAL': 'Diplomados',
    '1088 DIPLOMADO REDACCION Y ORTOGRAFIA PARA LA INGENIERIA': 'Diplomados',
    '1091 DIPLOMADO DESARROLLO DE PRACTICAS EMPRESARIALES': 'Diplomados',
    '1092 DIPLOMADO ENSEÑANZA DE LA MATEMATICA PARA DOCENTES': 'Diplomados',
    '1093 DIPLOMADO ESTRATEGIAS DE LECTURA PARA UNA COMPRENSION ANALITICA': 'Diplomados',
    '1094 DIPLOMADO ELABORACION, FORMULACION Y EVALUACION DE PROYECTOS DE INVERSION': 'Diplomados',
    '1095 DIPLOMADO MANEJO DE AGUAS RESIDUALES CON ENFASIS EN GESTION AMBIENTAL': 'Diplomados',
    '1096 DIPLOMADO DISEÑO Y ELABORACION DE PRESUPUESTO PARA OBRAS DE CONSTRUCCION': 'Diplomados',
    '3022 PSICOLOGIA INDUSTRIAL (DIPLOMADO)': 'Diplomados',
    '3116 MATEMATICA APLICADA 3 (DIPLOMADO)': 'Diplomados',
    '3118 MATEMATICA APLICADA 1 (DIPLOMADO)': 'Diplomados',
    '3120 MATEMATICA APLICADA 2 (DIPLOMADO)': 'Diplomados',
    '3123 MATEMATICA APLICADA 5 (DIPLOMADO)': 'Diplomados',
    '3606 ANALISIS DE SISTEMAS INDUSTRIALES (DIPLOMADO)': 'Diplomados',
    '3656 ADMINISTRACION DE EMPRESAS 1 (DIPLOMADO)': 'Diplomados',
    '3657 ADMINISTRACION DE EMPRESAS 2 (DIPLOMADO)': 'Diplomados',
    '3658 ADMINISTRACION DE PERSONAL (DIPLOMADO)': 'Diplomados',
    '3661 MERCADOTECNIA 2 (DIPLOMADO)': 'Diplomados',
    '3662 LEGISLACION 1 (DIPLOMADO)': 'Diplomados',
    '3664 LEGISLACION 2 (DIPLOMADO)': 'Diplomados',
    '3669 ECONOMIA INDUSTRIAL (DIPLOMADO)': 'Diplomados',
    '3710 PLANEAMIENTO (DIPLOMADO)': 'Diplomados',
    #Otros
    '0001 ETICA PROFESIONAL': 'Otro',
    '0006 IDIOMA TECNICO 1': 'Otro',
    '0008 IDIOMA TECNICO 2': 'Otro',
    '0009 IDIOMA TECNICO 3': 'Otro',
    '0010 LOGICA': 'Otro',
    '0011 IDIOMA TECNICO 4': 'Otro',
    '0019 AREA SOCIAL HUMANISTICA 2': 'Otro',
    '0030 GEOGRAFIA': 'Otro',
    '0040 DEPORTES 2': 'Otro',
    '0073 DIBUJO TECNICO MECANICO': 'Otro',
    '0074 DIBUJO CONSTRUCTIVO PARA INGENIERIA': 'Otro',
    '0366 ANALISIS INSTRUMENTAL': 'Otro',
    '0242 COMUNICACIONES 1': 'Otro',
    '0243 COMUNICACIONES 4': 'Otro',
    '0244 COMUNICACIONES 2': 'Otro',
    '0245 COMUNICACIONES 3': 'Otro',
    '5007 COMUNICACION Y REDACCION II': 'Otro',
    '0414 IQ-3 TRANSFERENCIA DE CALOR': 'Otro',
    '0416 IQ-4 TRANSFERENCIA DE MASA': 'Otro',
    '0418 IQ-5 TRANSFERENCIA DE MASA EN UNIDADES CONTINUAS': 'Otro',
    '0436 DISEÑO DE EQUIPO': 'Otro',
    '0439 INGENIERIA TEXTIL 2': 'Otro',
    '7980 INVESTIGACION 1': 'Otro',
    '0454 METALURGIA Y METALOGRAFIA': 'Otro',
    '0472 TECNOLOGIA DE LOS ALIMENTOS': 'Otro',
    '0532 VIBRACIONES': 'Otro',
    '0585 INGENIERIA DE TRANSITO Y TRANSPORTES': 'Otro',
    '0969 TELECOMUNICACIONES Y REDES LOCALES': 'Otro'
}

def categorizar1(cursos):
    # Paso 2: Crear un diccionario para almacenar los datos por categorías.
    categorias_dict = {categoria: [] for categoria in set(cursos_categorias.values())}

    # Paso 3: Procesar la cola.
    while cursos.primero:  # Asumiendo que cursos es una instancia de tu clase Cola
        nodo = cursos.desencolar()
        nombre_curso = nodo[0]  # El nombre del curso está en la posición 0 del nodo.

        # Verificar si el nombre del curso está en el diccionario de cursos_categorias
        if nombre_curso in cursos_categorias:
            categoria = cursos_categorias[nombre_curso]
            categorias_dict[categoria].append({
                'Nombre de Curso': nodo[0],
                'Star': nodo[1],
                'Seccion': nodo[2],
                'Modalidad': nodo[3],
                'Edificio': nodo[4],
                'Salon': nodo[5],
                'Inicio': nodo[6],
                'Final': nodo[7],
                'Dias': nodo[8],
                'Catedratico': nodo[9],
                'Aux': nodo[10],
                'Restricciones': nodo[11]
            })

    # Asegurarse de que la carpeta 'categorias' exista
    if not os.path.exists('categorias'):
        os.makedirs('categorias')

    # Paso 4: Guardar cada categoría como un archivo JSON.
    for categoria, cursos in categorias_dict.items():
        archivo_json = f'categorias/{categoria}.json'
        with open(archivo_json, 'w', encoding='utf-8') as json_file:
            json.dump(cursos, json_file, ensure_ascii=False, indent=4)

        print(f'Archivo JSON creado para la categoría: {categoria}')
